services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app            # Syncs your local code to /app in the container
      - /app/node_modules # Prevents local node_modules from overwriting container ones
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost}
      WATCHPACK_POLLING: "true"
